language: python
python:
- '3.6'
script:
- pytest
deploy:
  provider: heroku
  api_key:
    secure: G7iep3n2OupCUgM+wiw9OjAQQLb8l8q7L3O8npH86vNueZwMyAUZRYyUq9O+1KWj0SqqcB1B71Y4gd8T1OmqwnoEzvkFizRKzHc5991c9UI+2CodRtPwCvwlNl6WvNH6Pwwo8EsiYOgMy0+1Gt3BwwkaWND5Cqf8yuMChZKF7xEHGy32kodicS0SGLuF0eOQgQK6kYLuCDVP1Y2/hkxph02uPoqEHhTmd356i8WnqtrsI7d+C49yYbwy85moyiDNm3bRAGB2vjedU/BF++LH9KVnPmEJFJaqhoBY27p5r7cttvoeEc8cT+b9t3d8Nm8/9CWJ+4/neXcizEpKUPEjXl55G5YEJYT0PPfJ2Hon9nhNY7vn7yZAhPxsSUmleb0ATVFM8hUjdlm39EyBFgVeiwdRHQ4Agj7zDajuDtcf74cHMyR17Hcqfy5/nX4eprQrdjIuCxL/3PBGFY/QgMnWbKDgyH3fDo6BZWuEDuo9xnzK5GuiICD6ai+UnnDUeQmSvXPcfJMBYX5nJ87/JdhKBS+lMKC4WEJWgqwjnJQlD2JI8Ypg5cxIUic7Twk9eYhTlp/my2hTmfob6Yem50Q5S4W78k28Q8UODQL8RSn0vOYbjAcfkz4zhwbmVwqRV1ZGgSeb6oeWKqLLe3m8wkjncpA/ndCspMVcJ3khXPtA6KQ=
  app: acg-filter
  on:
    repo: lukaszkuczynski/filter
